# Generated by Django 3.2.6 on 2021-08-05 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='valoracion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='tarifa',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='user',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='valoracion',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(max_length=16, unique=True)),
                ('asunto', models.CharField(default='(Sin título)', max_length=64)),
                ('participantes', models.ManyToManyField(blank=True, related_name='participantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_enviado', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje', to='epy_api.sesion')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
